apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/vllm-whisper-turbo
resources:
  - namespace.yml
  - secret.yml
namespace: ai-models
patches:
  - path: isvc-patch.yml
    target:
      name: whisper-turbo
      kind: InferenceService