provider:
  name: cloudflare
policy: upsert-only
txtOwnerId: "production-cluster"
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-token
        key: cloudflare-dns-token
sources:
  - gateway-httproute
rbac:
  create: true
  additionalPermissions:
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get", "watch", "list"]
    - apiGroups: ["gateway.networking.k8s.io"]
      resources: ["gateways", "httproutes", "grpcroutes", "tlsroutes", "tcproutes", "udproutes"]
      verbs: ["get", "watch", "list"]