kserve:
  controller:
    deploymentMode: Standard
    disableIngressCreation: true
    gateway:
      domain: farag.tech
      kserveGateway: kube-system/production-gateway
      domainTemplate: '{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}'
      urlScheme: https
      ingressGateway:
        enableGatewayApi: true
        className: cilium
        createGateway: false